// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: parkir.proto

package parkir

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parkir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_parkir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_parkir_proto_rawDescGZIP(), []int{0}
}

type IdParkir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *IdParkir) Reset() {
	*x = IdParkir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parkir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdParkir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdParkir) ProtoMessage() {}

func (x *IdParkir) ProtoReflect() protoreflect.Message {
	mi := &file_parkir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdParkir.ProtoReflect.Descriptor instead.
func (*IdParkir) Descriptor() ([]byte, []int) {
	return file_parkir_proto_rawDescGZIP(), []int{1}
}

func (x *IdParkir) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdParkir) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type Kendaraan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plat string `protobuf:"bytes,2,opt,name=plat,proto3" json:"plat,omitempty"`
	Tipe string `protobuf:"bytes,3,opt,name=tipe,proto3" json:"tipe,omitempty"`
}

func (x *Kendaraan) Reset() {
	*x = Kendaraan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parkir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kendaraan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kendaraan) ProtoMessage() {}

func (x *Kendaraan) ProtoReflect() protoreflect.Message {
	mi := &file_parkir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kendaraan.ProtoReflect.Descriptor instead.
func (*Kendaraan) Descriptor() ([]byte, []int) {
	return file_parkir_proto_rawDescGZIP(), []int{2}
}

func (x *Kendaraan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Kendaraan) GetPlat() string {
	if x != nil {
		return x.Plat
	}
	return ""
}

func (x *Kendaraan) GetTipe() string {
	if x != nil {
		return x.Tipe
	}
	return ""
}

type BayarParkir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price   int64  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Plat    string `protobuf:"bytes,3,opt,name=plat,proto3" json:"plat,omitempty"`
	Tipe    string `protobuf:"bytes,4,opt,name=tipe,proto3" json:"tipe,omitempty"`
	TMasuk  string `protobuf:"bytes,5,opt,name=TMasuk,proto3" json:"TMasuk,omitempty"`
	TKeluar string `protobuf:"bytes,6,opt,name=TKeluar,proto3" json:"TKeluar,omitempty"`
}

func (x *BayarParkir) Reset() {
	*x = BayarParkir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parkir_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BayarParkir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BayarParkir) ProtoMessage() {}

func (x *BayarParkir) ProtoReflect() protoreflect.Message {
	mi := &file_parkir_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BayarParkir.ProtoReflect.Descriptor instead.
func (*BayarParkir) Descriptor() ([]byte, []int) {
	return file_parkir_proto_rawDescGZIP(), []int{3}
}

func (x *BayarParkir) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BayarParkir) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BayarParkir) GetPlat() string {
	if x != nil {
		return x.Plat
	}
	return ""
}

func (x *BayarParkir) GetTipe() string {
	if x != nil {
		return x.Tipe
	}
	return ""
}

func (x *BayarParkir) GetTMasuk() string {
	if x != nil {
		return x.TMasuk
	}
	return ""
}

func (x *BayarParkir) GetTKeluar() string {
	if x != nil {
		return x.TKeluar
	}
	return ""
}

var File_parkir_proto protoreflect.FileDescriptor

var file_parkir_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x2e, 0x0a, 0x08, 0x49, 0x64, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0x43, 0x0a, 0x09, 0x4b, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x61, 0x61, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6c, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x70, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x42, 0x61, 0x79, 0x61, 0x72, 0x50, 0x61,
	0x72, 0x6b, 0x69, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6c,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x54, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x4b,
	0x65, 0x6c, 0x75, 0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x4b, 0x65,
	0x6c, 0x75, 0x61, 0x72, 0x32, 0x74, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x12, 0x30,
	0x0a, 0x0b, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x12, 0x0d, 0x2e,
	0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x70,
	0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x49, 0x64, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x22, 0x00,
	0x12, 0x38, 0x0a, 0x0c, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72,
	0x12, 0x11, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x4b, 0x65, 0x6e, 0x64, 0x61, 0x72,
	0x61, 0x61, 0x6e, 0x1a, 0x13, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x42, 0x61, 0x79,
	0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_parkir_proto_rawDescOnce sync.Once
	file_parkir_proto_rawDescData = file_parkir_proto_rawDesc
)

func file_parkir_proto_rawDescGZIP() []byte {
	file_parkir_proto_rawDescOnce.Do(func() {
		file_parkir_proto_rawDescData = protoimpl.X.CompressGZIP(file_parkir_proto_rawDescData)
	})
	return file_parkir_proto_rawDescData
}

var file_parkir_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_parkir_proto_goTypes = []interface{}{
	(*Empty)(nil),       // 0: parkir.Empty
	(*IdParkir)(nil),    // 1: parkir.IdParkir
	(*Kendaraan)(nil),   // 2: parkir.Kendaraan
	(*BayarParkir)(nil), // 3: parkir.BayarParkir
}
var file_parkir_proto_depIdxs = []int32{
	0, // 0: parkir.parkir.MasukParkir:input_type -> parkir.Empty
	2, // 1: parkir.parkir.KeluarParkir:input_type -> parkir.Kendaraan
	1, // 2: parkir.parkir.MasukParkir:output_type -> parkir.IdParkir
	3, // 3: parkir.parkir.KeluarParkir:output_type -> parkir.BayarParkir
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parkir_proto_init() }
func file_parkir_proto_init() {
	if File_parkir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parkir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parkir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdParkir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parkir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kendaraan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parkir_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BayarParkir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parkir_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parkir_proto_goTypes,
		DependencyIndexes: file_parkir_proto_depIdxs,
		MessageInfos:      file_parkir_proto_msgTypes,
	}.Build()
	File_parkir_proto = out.File
	file_parkir_proto_rawDesc = nil
	file_parkir_proto_goTypes = nil
	file_parkir_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ParkirClient is the client API for Parkir service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParkirClient interface {
	MasukParkir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdParkir, error)
	KeluarParkir(ctx context.Context, in *Kendaraan, opts ...grpc.CallOption) (*BayarParkir, error)
}

type parkirClient struct {
	cc grpc.ClientConnInterface
}

func NewParkirClient(cc grpc.ClientConnInterface) ParkirClient {
	return &parkirClient{cc}
}

func (c *parkirClient) MasukParkir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdParkir, error) {
	out := new(IdParkir)
	err := c.cc.Invoke(ctx, "/parkir.parkir/MasukParkir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkirClient) KeluarParkir(ctx context.Context, in *Kendaraan, opts ...grpc.CallOption) (*BayarParkir, error) {
	out := new(BayarParkir)
	err := c.cc.Invoke(ctx, "/parkir.parkir/KeluarParkir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParkirServer is the server API for Parkir service.
type ParkirServer interface {
	MasukParkir(context.Context, *Empty) (*IdParkir, error)
	KeluarParkir(context.Context, *Kendaraan) (*BayarParkir, error)
}

// UnimplementedParkirServer can be embedded to have forward compatible implementations.
type UnimplementedParkirServer struct {
}

func (*UnimplementedParkirServer) MasukParkir(context.Context, *Empty) (*IdParkir, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MasukParkir not implemented")
}
func (*UnimplementedParkirServer) KeluarParkir(context.Context, *Kendaraan) (*BayarParkir, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeluarParkir not implemented")
}

func RegisterParkirServer(s *grpc.Server, srv ParkirServer) {
	s.RegisterService(&_Parkir_serviceDesc, srv)
}

func _Parkir_MasukParkir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkirServer).MasukParkir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parkir.parkir/MasukParkir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkirServer).MasukParkir(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parkir_KeluarParkir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Kendaraan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkirServer).KeluarParkir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parkir.parkir/KeluarParkir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkirServer).KeluarParkir(ctx, req.(*Kendaraan))
	}
	return interceptor(ctx, in, info, handler)
}

var _Parkir_serviceDesc = grpc.ServiceDesc{
	ServiceName: "parkir.parkir",
	HandlerType: (*ParkirServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MasukParkir",
			Handler:    _Parkir_MasukParkir_Handler,
		},
		{
			MethodName: "KeluarParkir",
			Handler:    _Parkir_KeluarParkir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parkir.proto",
}
